# Generated by Django 2.2 on 2020-11-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20201108_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
