# Generated by Django 2.2 on 2020-11-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20201109_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='parole',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
